Insert Into tblClient
(
	FirstName
    ,MiddleName
    ,LastName
    ,AccountStatusID
    ,BlockNo
    ,LotNo
    ,Occupants
    ,IsSenior
    ,SeniorCount
    ,PreviousReading
)
Values
(
    '@_FirstName',
    '@_MiddleName',
    '@_LastName',
    @_ClientAccountStatusID,
    @_BlockNo,
    @_LotNo,
    @_Occupants,
    '@_IsSenior',
    @_SeniorCount,
    @_PreviousReading
)